### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/biffud.com#33] opened 2018-05-16 11:41 UTC
I propose that the 404 page on BIFFUD to start a Win98 (from a saved state) that opens MSIE5 to show the real 404 page

https://copy.sh/v86/?profile=windows98 click on *load state* and feed this file: https://thegpf.slack.com/files/U04MYCVMC/FAQNAA7NE/v86state.bin

Screenshot:

![screenshot 2018-05-16 19 39 06](https://user-images.githubusercontent.com/21679/40114842-ed7205da-5940-11e8-80d8-05794c22d7ab.png)

We can have those scripts loading this image automatically, all nice custom html/js

Note: that sheep.exe is active and running ;)

**Comment by chriszs** [comment] 2018-05-28 16:35
Closing as a dupe of #1

**Closed by chriszs** 2018-05-28 16:35 UTC
